# Generated by Django 2.0.7 on 2018-07-16 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brochure', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Affiliates',
            new_name='Affiliate',
        ),
    ]
