# Generated by Django 2.0.7 on 2018-07-19 00:48

import brochure.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brochure', '0002_auto_20180716_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='abstract',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='degree',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='photo',
            field=models.ImageField(blank=True, upload_to=brochure.models.format_photo_path),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='subject',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
