# Generated by Django 2.0.7 on 2018-07-19 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brochure', '0003_auto_20180719_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliate',
            name='link',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
