# Generated by Django 2.0.7 on 2018-07-27 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brochure', '0006_auto_20180719_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='chin_name',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
