# Generated by Django 2.0.7 on 2018-07-28 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brochure', '0007_speaker_chin_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metatag',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
